/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TCropDetails, TRegionHotspots } from "./components/information-card/types";
export { TCropDetails, TRegionHotspots } from "./components/information-card/types";
export namespace Components {
    interface InformationCard {
        "accessToken": string;
        /**
          * @function to convert api response (TRegionHotspots) to our desired type (Array<TCropDetails>) - iterates over the response array  - group them by cropId
         */
        "groupObjectsByCropId": (inputArray: TRegionHotspots) => Promise<Array<TCropDetails>>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLInformationCardElement extends Components.InformationCard, HTMLStencilElement {
    }
    var HTMLInformationCardElement: {
        prototype: HTMLInformationCardElement;
        new (): HTMLInformationCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "information-card": HTMLInformationCardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface InformationCard {
        "accessToken"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "information-card": InformationCard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "information-card": LocalJSX.InformationCard & JSXBase.HTMLAttributes<HTMLInformationCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
